In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# pip install tensorflow
# !pip install tensorflow

In [3]:
import tensorflow as tf

In [4]:
print(tf.__version__)

2.6.0


#### TF Basics
1) Tensors are like numpy array<br>
2) Tensors are multi-dimensional arrys with uniform data type(referred to as dtype)<br>
3) All tensors are immutable like Python numbers and strings. They cant be updated<br>

In [8]:
r0t = tf.constant(76)
print(r0t)
print(r0t.numpy())
print(r0t.dtype)
print(r0t.ndim)
print(r0t.shape)

tf.Tensor(76, shape=(), dtype=int32)
76
<dtype: 'int32'>
0
()


In [13]:
r1t = tf.constant([1,2,3,4,5,6,7])
print(r1t)
print(r1t.numpy())
print(r1t.dtype)
print(r1t.ndim)
print(r1t.shape)

tf.Tensor([1 2 3 4 5 6 7], shape=(7,), dtype=int32)
[1 2 3 4 5 6 7]
<dtype: 'int32'>
1
(7,)


In [14]:
r2t = tf.constant([[1,2,3],[4,55,6]])
print(r2t)
print(r2t.numpy())
print(r2t.dtype)
print(r2t.ndim)
print(r2t.shape)

tf.Tensor(
[[ 1  2  3]
 [ 4 55  6]], shape=(2, 3), dtype=int32)
[[ 1  2  3]
 [ 4 55  6]]
<dtype: 'int32'>
2
(2, 3)


In [16]:
r3t = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(r3t)
print(r3t.numpy())
print(r3t.dtype)
print(r3t.ndim)
print(r3t.shape)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<dtype: 'int32'>
3
(2, 2, 3)


#### Tensors are immutable

In [18]:
w1 = tf.constant([3,4,5,6,7,8])
print(w1.numpy())
print(w1[0].numpy())
w1[0] = 50
print(w1)

[3 4 5 6 7 8]
3


TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

#### Tensroflow Operations

In [20]:
a1 = tf.constant([[1,2],[3,4]])
a2 = tf.constant([[7,10],[6,20]])

print(tf.add(a1,a2).numpy())
print(tf.subtract(a2,a1).numpy())
print(tf.multiply(a1,a2).numpy()) # element wise multiplication
print(tf.divide(a2,a1).numpy())

[[ 8 12]
 [ 9 24]]
[[ 6  8]
 [ 3 16]]
[[ 7 20]
 [18 80]]
[[7. 5.]
 [2. 5.]]


In [22]:
print(a1+a2)
print(a2-a1)
print(a1*a2)
print(a2/a1)

tf.Tensor(
[[ 8 12]
 [ 9 24]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 6  8]
 [ 3 16]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 7 20]
 [18 80]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[7. 5.]
 [2. 5.]], shape=(2, 2), dtype=float64)


#### Architecture for Neural Network

In [25]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

#### ANN Model for Regression
1) Activation function used in hidden layer  - relu, leakyrelu<br>
2) Activation function used in output layer  - linear<br>
3) Optimizer - adam, rmsprop, sgd<br>
4) Loss Function - mse, mae<br>


In [ ]:
# Suppose shape of x(independent feature) = (200,8)
# Rows = 200, Columns = 8

In [27]:
m1 = Sequential()                                 # Input layer has 8 neurons
m1.add(Dense(32,activation='relu',input_dim=8))   # H1 has 32 neurons
m1.add(Dense(16,activation='relu'))               # H2 has 16 neurons
m1.add(Dense(8,activation='relu'))                # H3 has 8 neurons
m1.add(Dense(1))                                  # Output layer has 1 neuron, activation='linear'

m1.compile(optimizer='adam',loss='mse')

In [28]:
m1.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 32)                288       
_________________________________________________________________
dense_5 (Dense)              (None, 16)                528       
_________________________________________________________________
dense_6 (Dense)              (None, 8)                 136       
_________________________________________________________________
dense_7 (Dense)              (None, 1)                 9         
Total params: 961
Trainable params: 961
Non-trainable params: 0
_________________________________________________________________


#### ANN Model for Binary Classification 

1) Activation function used in hidden layer  - relu, leakyrelu<br>
2) Activation function used in output layer  - sigmoid<br>
3) Optimizer - adam, rmsprop, sgd<br>
4) Loss Function - binary_crossentropy<br>
